d,root,my_project
d,root\my_project,settings
-,root\my_project\settings,__init__.py
-,root\my_project\settings,dev.py
-,root\my_project\settings,prod.py
d,root\my_project,mainapp
-,root\my_project\mainapp,__init__.py
-,root\my_project\mainapp,models.py
-,root\my_project\mainapp,views.py
d,root\my_project\mainapp,templates
d,root\my_project\mainapp\templates,mainapp
-,root\my_project\mainapp\templates\mainapp,base.html
-,root\my_project\mainapp\templates\mainapp,index.html
d,root\my_project,authapp
-,root\my_project\authapp,__init__.py
-,root\my_project\authapp,models.py
-,root\my_project\authapp,views.py
d,root\my_project\authapp,templates
d,root\my_project\authapp\templates,authapp
-,root\my_project\authapp\templates\authapp,base.html
-,root\my_project\authapp\templates\authapp,index.html